import { User } from '../models/User.js';
import { EMPLOYEE_CODE_REGEX } from '../../../shared/validation/employee.js';

/** Auto-generated codes use prefix EMP + zero-padded sequence (EMP001, EMP102, …). */
const AUTO_PREFIX = 'EMP';
const MAX_CREATE_ATTEMPTS = 8;

export function normalizeEmployeeCode(value) {
  if (value === undefined || value === null) return '';
  const trimmed = String(value).trim();
  if (!trimmed) return '';
  return trimmed.toUpperCase();
}

export function isValidEmployeeCodeFormat(code) {
  return EMPLOYEE_CODE_REGEX.test(code);
}

/**
 * Finds the next EMP### code by scanning existing EMP+digits values.
 * Unique index + retry in createEmployee handles concurrent allocation races.
 */
export async function allocateNextEmployeeCode() {
  const users = await User.find({
    employeeCode: { $regex: /^EMP\d+$/i },
  })
    .select('employeeCode')
    .lean();

  let maxNum = 0;
  for (const user of users) {
    const match = String(user.employeeCode).match(/^EMP(\d+)$/i);
    if (match) {
      maxNum = Math.max(maxNum, parseInt(match[1], 10));
    }
  }

  return `${AUTO_PREFIX}${String(maxNum + 1).padStart(3, '0')}`;
}

export async function resolveEmployeeCodeForCreate(rawCode) {
  const normalized = normalizeEmployeeCode(rawCode);
  if (normalized) {
    return { code: normalized, autoGenerated: false };
  }
  return { code: await allocateNextEmployeeCode(), autoGenerated: true };
}

export function duplicateFieldMessage(field) {
  const messages = {
    email: 'This email is already registered.',
    mobile: 'This mobile number is already registered.',
    employeeCode: 'Employee code already in use.',
  };
  return messages[field] ?? `Duplicate value for ${field}.`;
}

export function enrichDuplicateKeyError(error) {
  if (error?.code !== 11000) {
    return error;
  }
  const field = Object.keys(error.keyPattern ?? {})[0] ?? 'field';
  const duplicateError = new Error(duplicateFieldMessage(field));
  duplicateError.statusCode = 409;
  duplicateError.field = field;
  duplicateError.code = 11000;
  return duplicateError;
}

export { MAX_CREATE_ATTEMPTS };
