import bcrypt from 'bcryptjs';
import * as XLSX from 'xlsx';
import { z } from 'zod';
import { User } from '../models/User.js';
import { Department } from '../models/Department.js';
import { buildEmployeeInputSchema } from '../../../shared/validation/employee.js';
import {
  MAX_BULK_UPLOAD_ROWS,
  normalizeMobile,
} from '../../../shared/validation/common.js';
import {
  legacyRoleFromSlug,
  prepareEmployeeReferences,
  resolveDepartment,
  resolveManagedDepartments,
  resolveReportingManager,
  resolveRole,
} from './userOrgService.js';
import {
  allocateNextEmployeeCode,
  duplicateFieldMessage,
  enrichDuplicateKeyError,
  MAX_CREATE_ATTEMPTS,
  normalizeEmployeeCode,
  resolveEmployeeCodeForCreate,
} from './employeeCodeService.js';

export { normalizeMobile };

async function persistEmployee(parsed, passwordHash, role, department, manager, managedDepartments, createdBy) {
  let autoGenerated = false;
  let employeeCode = normalizeEmployeeCode(parsed.employeeCode);

  if (!employeeCode) {
    const resolved = await resolveEmployeeCodeForCreate('');
    employeeCode = resolved.code;
    autoGenerated = true;
  }

  for (let attempt = 0; attempt < MAX_CREATE_ATTEMPTS; attempt += 1) {
    try {
      const user = await User.create({
        role: legacyRoleFromSlug(role.slug),
        roleId: role._id,
        firstName: parsed.firstName,
        lastName: parsed.lastName,
        name: `${parsed.firstName} ${parsed.lastName}`.trim(),
        email: parsed.email.toLowerCase(),
        mobile: parsed.mobile,
        employeeCode,
        designation: parsed.designation || undefined,
        joiningDate: parsed.joiningDate,
        endingDate: parsed.endingDate ?? null,
        department: department?.name ?? parsed.department ?? undefined,
        departmentId: department?._id ?? undefined,
        reportingManagerId: manager?._id ?? undefined,
        managedDepartmentIds: managedDepartments,
        passwordHash,
        createdBy,
        isActive: true,
      });

      await user.populate([
        { path: 'roleId', select: 'name slug permissions isSystem' },
        { path: 'departmentId', select: 'name code isActive' },
        { path: 'reportingManagerId', select: 'name email' },
      ]);

      return user.toSafeJSON();
    } catch (error) {
      const duplicate = enrichDuplicateKeyError(error);
      if (duplicate !== error) {
        if (autoGenerated && duplicate.field === 'employeeCode') {
          employeeCode = await allocateNextEmployeeCode();
          continue;
        }
        throw duplicate;
      }
      throw error;
    }
  }

  const exhausted = new Error('Unable to allocate a unique employee code. Please try again.');
  exhausted.statusCode = 409;
  throw exhausted;
}

function stripBulkReferenceFields(data) {
  const {
    reportingManagerEmail: _reportingManagerEmail,
    reportingManagerCode: _reportingManagerCode,
    ...schemaInput
  } = data;
  return schemaInput;
}

export async function createEmployee(data, createdBy, options = {}) {
  const role = await resolveRole(data.roleId);
  const hasDepartments = (await Department.countDocuments({ isActive: true })) > 0;
  const prepared = await prepareEmployeeReferences(data, { roleSlug: role.slug, hasDepartments });
  const parsed = buildEmployeeInputSchema({
    roleSlug: role.slug,
    hasDepartments,
    bulkImport: options.bulkImport === true,
  }).parse(stripBulkReferenceFields(prepared));
  const passwordHash = await bcrypt.hash(parsed.password, 12);
  const department = await resolveDepartment(parsed);
  const manager = parsed.reportingManagerId
    ? await resolveReportingManager(parsed.reportingManagerId)
    : null;
  const managedDepartments = parsed.managedDepartmentIds?.length
    ? await resolveManagedDepartments(parsed.managedDepartmentIds)
    : [];

  return persistEmployee(
    parsed,
    passwordHash,
    role,
    department,
    manager,
    managedDepartments,
    createdBy,
  );
}

function normalizeHeader(value) {
  return String(value ?? '')
    .trim()
    .toLowerCase()
    .replace(/\s+/g, '');
}

const headerMap = {
  firstname: 'firstName',
  lastname: 'lastName',
  email: 'email',
  mobile: 'mobile',
  password: 'password',
  employeecode: 'employeeCode',
  employeeid: 'employeeCode',
  department: 'department',
  designation: 'designation',
  reportingmanageremail: 'reportingManagerEmail',
  reportingmanagercode: 'reportingManagerCode',
  joiningdate: 'joiningDate',
  endingdate: 'endingDate',
};

const DATE_FIELDS = new Set(['joiningDate', 'endingDate']);

function formatIsoDateParts(year, month, day) {
  return `${year}-${String(month).padStart(2, '0')}-${String(day).padStart(2, '0')}`;
}

function excelSerialToIsoDate(serial) {
  if (!Number.isFinite(serial)) {
    return '';
  }

  let adjusted = serial;
  if (adjusted >= 60) {
    adjusted -= 1;
  }

  const date = new Date(Date.UTC(1899, 11, 30) + adjusted * 86400000);
  if (Number.isNaN(date.getTime())) {
    return '';
  }

  return formatIsoDateParts(date.getUTCFullYear(), date.getUTCMonth() + 1, date.getUTCDate());
}

/** Normalize Excel date cells (serials, Date objects, or text) to YYYY-MM-DD or ''. */
export function normalizeExcelDateCell(value) {
  if (value === null || value === undefined || value === '') {
    return '';
  }

  if (value instanceof Date) {
    if (Number.isNaN(value.getTime())) {
      return '';
    }
    return formatIsoDateParts(value.getFullYear(), value.getMonth() + 1, value.getDate());
  }

  if (typeof value === 'number') {
    return excelSerialToIsoDate(value);
  }

  const trimmed = String(value).trim();
  if (!trimmed) {
    return '';
  }

  if (/^\d{4}-\d{2}-\d{2}$/.test(trimmed)) {
    return trimmed;
  }

  const ddMmYyyy = trimmed.match(/^(\d{1,2})[/-](\d{1,2})[/-](\d{4})$/);
  if (ddMmYyyy) {
    const day = Number(ddMmYyyy[1]);
    const month = Number(ddMmYyyy[2]);
    const year = Number(ddMmYyyy[3]);
    if (month >= 1 && month <= 12 && day >= 1 && day <= 31) {
      return formatIsoDateParts(year, month, day);
    }
  }

  return trimmed;
}

function normalizeCellValue(target, value) {
  if (DATE_FIELDS.has(target)) {
    return normalizeExcelDateCell(value);
  }
  return String(value ?? '').trim();
}

export function parseEmployeeWorkbook(buffer) {
  const workbook = XLSX.read(buffer, { type: 'buffer' });
  const sheetName = workbook.SheetNames[0];
  if (!sheetName) {
    throw new Error('The uploaded Excel file does not contain any sheets.');
  }

  const rows = XLSX.utils.sheet_to_json(workbook.Sheets[sheetName], {
    defval: '',
  });

  if (rows.length > MAX_BULK_UPLOAD_ROWS) {
    throw new Error(
      `The file contains ${rows.length} rows. Maximum allowed is ${MAX_BULK_UPLOAD_ROWS}.`,
    );
  }

  return rows.map((row, index) => {
    const mapped = {};
    for (const [key, value] of Object.entries(row)) {
      const normalized = normalizeHeader(key);
      const target = headerMap[normalized];
      if (target) {
        mapped[target] = normalizeCellValue(target, value);
      }
    }
    return { rowNumber: index + 2, data: mapped };
  });
}

function partitionRowsByFileDuplicates(rows) {
  const seenEmail = new Map();
  const seenMobile = new Map();
  const seenCode = new Map();
  const duplicates = [];
  const uniqueRows = [];

  for (const row of rows) {
    const email = String(row.data.email ?? '')
      .trim()
      .toLowerCase();
    const mobile = normalizeMobile(row.data.mobile);
    const employeeCode = normalizeEmployeeCode(row.data.employeeCode);

    if (email && seenEmail.has(email)) {
      duplicates.push({
        rowNumber: row.rowNumber,
        status: 'duplicate',
        email: row.data.email ?? '',
        message: `Duplicate email within file (first seen on row ${seenEmail.get(email)}).`,
      });
      continue;
    }

    if (mobile && seenMobile.has(mobile)) {
      duplicates.push({
        rowNumber: row.rowNumber,
        status: 'duplicate',
        email: row.data.email ?? '',
        message: `Duplicate mobile within file (first seen on row ${seenMobile.get(mobile)}).`,
      });
      continue;
    }

    if (employeeCode && seenCode.has(employeeCode)) {
      duplicates.push({
        rowNumber: row.rowNumber,
        status: 'duplicate',
        email: row.data.email ?? '',
        message: `Duplicate employee code within file (first seen on row ${seenCode.get(employeeCode)}).`,
      });
      continue;
    }

    if (email) seenEmail.set(email, row.rowNumber);
    if (mobile) seenMobile.set(mobile, row.rowNumber);
    if (employeeCode) seenCode.set(employeeCode, row.rowNumber);
    uniqueRows.push(row);
  }

  return { duplicates, uniqueRows };
}

export async function importEmployeesFromRows(rows, createdBy) {
  const { duplicates: fileDuplicates, uniqueRows } = partitionRowsByFileDuplicates(rows);
  const results = [...fileDuplicates];

  for (const row of uniqueRows) {
    try {
      const employee = await createEmployee(row.data, createdBy, { bulkImport: true });
      results.push({
        rowNumber: row.rowNumber,
        status: 'success',
        email: employee.email,
        message: 'Employee registered successfully.',
      });
    } catch (error) {
      if (error.code === 11000 || error.statusCode === 409) {
        const field = error.field ?? Object.keys(error.keyPattern ?? {})[0];
        results.push({
          rowNumber: row.rowNumber,
          status: 'duplicate',
          email: row.data.email ?? '',
          message: field ? duplicateFieldMessage(field) : 'Duplicate email, mobile, or employee code.',
        });
        continue;
      }

      if (error instanceof z.ZodError) {
        results.push({
          rowNumber: row.rowNumber,
          status: 'validation_error',
          email: row.data.email ?? '',
          message: error.issues.map((issue) => issue.message).join(' '),
        });
        continue;
      }

      if (error.statusCode === 400) {
        results.push({
          rowNumber: row.rowNumber,
          status: 'validation_error',
          email: row.data.email ?? '',
          message: error.message ?? 'Validation failed.',
        });
        continue;
      }

      results.push({
        rowNumber: row.rowNumber,
        status: 'error',
        email: row.data.email ?? '',
        message: error.message ?? 'Failed to register employee.',
      });
    }
  }

  results.sort((a, b) => a.rowNumber - b.rowNumber);

  const summary = {
    total: results.length,
    success: results.filter((item) => item.status === 'success').length,
    duplicate: results.filter((item) => item.status === 'duplicate').length,
    validation_error: results.filter(
      (item) => item.status === 'validation_error',
    ).length,
    error: results.filter((item) => item.status === 'error').length,
  };

  return { summary, results };
}

export function buildEmployeeTemplateWorkbook() {
  const worksheet = XLSX.utils.aoa_to_sheet([
    [
      'firstName',
      'lastName',
      'email',
      'mobile',
      'password',
      'employeeCode',
      'department',
      'designation',
      'reportingManagerEmail',
      'reportingManagerCode',
      'joiningDate',
      'endingDate',
    ],
    [
      'Jane',
      'Doe',
      'jane@grubpac.com',
      '9876543210',
      'Employee@123',
      'EMP001',
      'Development',
      'Software Engineer',
      'manager@grubpac.com',
      'TL001',
      '2026-01-15',
      '',
    ],
  ]);
  const workbook = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(workbook, worksheet, 'Employees');
  return XLSX.write(workbook, { type: 'buffer', bookType: 'xlsx' });
}
